Vagrant::Config.run do |config|
  # Setup the box
  config.vm.box = "ubuntu-precise-64"

  # Enable the Puppet provisioner
  config.vm.provision :puppet

  # Enable and configure the chef solo provisioner
  config.vm.provision :chef_solo do |chef|
    # We're going to download our cookbooks from the web
    chef.recipe_url = "http://files.vagrantup.com/getting_started/cookbooks.tar.gz"

    # Tell chef what recipe to run. In this case, the `vagrant_main` recipe
    # does all the magic.
    chef.add_recipe("vagrant_main")
  end

  # Some NFS testing
  config.vm.share_folder("v-root", "/vagrant", ".", :nfs => true)

  # Static host-only IP
  config.vm.network :hostonly, "10.0.73.57"
end
